//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemainierStage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tache
    {
        public int Id { get; set; }
        public string Commentaire { get; set; }
        public System.DateTime Date { get; set; }
        public int Etudiant_ID { get; set; }
        public decimal NombreHeures { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
    }
}
